# Image ubuntu:22.04 used for all fingerprinters env (except dev) for consistent fingerprint generation
FROM ubuntu:22.04

ARG FPCALC_INTERNAL_PATH
ARG DOCKERIZED_POOL_DIR
ARG DOCKERIZED_FLASK_LOG_DIR
ARG FLASK_LOG_APP_FILENAME
ARG FLASK_LOG_ERROR_FILENAME
ARG FLASK_LOG_REQUESTS_FILENAME
ARG GUNICORN_LOG_DIR
ARG GUNICORN_LOG_ERROR_FILENAME
ARG GUNICORN_LOG_ACCESS_FILENAME


RUN for var in \
    FPCALC_INTERNAL_PATH \
    DOCKERIZED_POOL_DIR \
    DOCKERIZED_FLASK_LOG_DIR \
    FLASK_LOG_APP_FILENAME \
    FLASK_LOG_ERROR_FILENAME \
    FLASK_LOG_REQUESTS_FILENAME \
    GUNICORN_LOG_DIR \
    GUNICORN_LOG_ERROR_FILENAME \
    GUNICORN_LOG_ACCESS_FILENAME; do \
    if [ -z "$(eval echo \$$var)" ]; then \
        echo "The $var argument is not provided" >&2; \
        exit 1; \
    fi; \
done

ENV APP_IS_DOCKERIZED=true \
    APP_IS_EXPOSED=true \
    ENV=TEST \
    FPCALC_INTERNAL_PATH=$FPCALC_INTERNAL_PATH \
    DOCKERIZED_POOL_DIR=$DOCKERIZED_POOL_DIR \
    FLASK_LOGS_ARE_NEEDED=true \
    DOCKERIZED_FLASK_LOG_DIR=$DOCKERIZED_FLASK_LOG_DIR \
    FLASK_LOG_APP_FILENAME=$FLASK_LOG_APP_FILENAME \
    FLASK_LOG_ERROR_FILENAME=$FLASK_LOG_ERROR_FILENAME \
    FLASK_LOG_REQUESTS_FILENAME=$FLASK_LOG_REQUESTS_FILENAME \
    GUNICORN_LOG_DIR=$GUNICORN_LOG_DIR \
    GUNICORN_LOG_ERROR_FILENAME=$GUNICORN_LOG_ERROR_FILENAME \
    GUNICORN_LOG_ACCESS_FILENAME=$GUNICORN_LOG_ACCESS_FILENAME

WORKDIR /app

COPY . .
RUN chmod +x scripts/setup_filesystem.sh && \
    bash scripts/setup_filesystem.sh && \
    bash scripts/install_dependencies.sh && \
    python3.12 -m pip install --no-cache-dir --ignore-installed -r requirements.txt && \
    chmod +x entrypoint.sh

ENTRYPOINT ["/app/entrypoint.sh"]