name: Audio Fingerprinter CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

env:
  IMAGE_REPO: ${{ vars.AUDIO_FINGERPRINTER_IMAGE_REPO }}
  IMAGE_TAG: ${{ vars.IMAGE_TAG }}
  SSH_DESTINATION: ${{ secrets.TEST_SERVER_BODZIFY_USERNAME }}@${{ vars.TEST_SERVER_URL }}
  DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
  TEST_SERVER_URL: ${{ vars.TEST_SERVER_URL }}
  ENV_VARIABLES_FILENAME: ${{ vars.ENV_VARIABLES_FILENAME }}

jobs:

  tests:
    name: Tests
    runs-on: ubuntu-22.04
    environment:
      name: CI_TEST
    env:
      ENV: CI_TEST
      APP_PORT: ${{ secrets.APP_PORT }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install -r requirements.txt

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg=7:4.4.2-0ubuntu0.22.04.1

      - name: Add right fpcalc to PATH
        run: |
          cp ${{ github.workspace }}/env/fpcalc/fpcalc-ubuntu ${{ github.workspace }}/bin/fpcalc
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      - name: Set up filesystem
        run: bash ${{ github.workspace }}/scripts/setup_filesystem.sh

      - name: Run tests
        run: python -m unittest discover

  build-and-push-to-dockerhub:
    name: Build / Push to DockerHub
    needs: tests
    runs-on: ubuntu-latest
    environment:
      name: TEST

    steps:
      - uses: actions/checkout@v4

      - name: Login to Dockerhub
        run: echo "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}" | docker login -u "${{ env.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG }}
          build-args: |
            POOL_DIR_SYMLINK_TARGET=${{ vars.AUDIO_FINGERPRINTER_POOL_SYMLINK_TARGET }}
            LOG_DIR_SYMLINK_TARGET=${{ vars.AUDIO_FINGERPRINTER_LOG_SYMLINK_TARGET }}

  redeploy-webhook-call:
    name: Redeploy webhook call
    needs: [build-and-push-to-dockerhub]
    uses: Bodzify/bodzify-server-management/.github/workflows/call-redeployment-webhook.yml@main
    with:
      env: TEST
    secrets: inherit
