name: Audio Fingerprinter CI

on:
  push:
    branches: [main, dev, improve-deployment]
  pull_request:
    branches: [main, dev, improve-deployment]
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-22.04
    environment:
      name: CI_TEST
    env:
      FPCALC: ${{ vars.FPCALC_INTERNAL_PATH }}
      ENV: ${{ vars.ENV }}
      APP_IS_DOCKERIZED: false
      DEBUG: true
      APP_IS_EXPOSED: false
      APP_PORT: ${{ secrets.APP_PORT }}
      POOL_INTERNAL_DIR: ${{ vars.POOL_INTERNAL_DIR }}
      FLASK_LOGS_ARE_NEEDED: false
      FLASK_LOG_INTERNAL_DIR: ${{ vars.FLASK_LOG_INTERNAL_DIR }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies & python requirements
        run: |
          sudo -E bash scripts/install_dependencies.sh
          python -m pip install --upgrade pip && pip install -r requirements.txt

      - name: Set up filesystem
        run: bash scripts/setup_filesystem.sh

      - name: Run tests
        run: python -m unittest discover

  build-and-push-to-dockerhub:
    name: Build / Push to DockerHub
    needs: tests
    runs-on: ubuntu-latest
    environment:
      name: TEST
    steps:
      - uses: actions/checkout@v4

      - name: Login to Dockerhub
        run: echo "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}" | docker login -u "${{ env.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.AFP_IMAGE_REPO }}:${{ vars.APP_VERSION }}
          build-args: |
            FPCALC_INTERNAL_PATH=${{ vars.FPCALC_INTERNAL_PATH }}
            DOCKERIZED_POOL_DIR=${{ vars.AFP_DOCKERIZED_POOL_DIR }}
            DOCKERIZED_FLASK_LOG_DIR=${{ vars.AFP_DOCKERIZED_FLASK_LOG_DIR }}
            FLASK_LOG_APP_FILENAME=${{ vars.FLASK_LOG_APP_FILENAME }}
            FLASK_LOG_ERROR_FILENAME=${{ vars.FLASK_LOG_ERROR_FILENAME }}
            FLASK_LOG_REQUESTS_FILENAME=${{ vars.FLASK_LOG_REQUESTS_FILENAME }}
            GUNICORN_LOG_DIR=${{ vars.AFP_DOCKERIZED_GUNICORN_LOG_DIR }}
            GUNICORN_LOG_ACCESS_FILENAME=${{ vars.GUNICORN_LOG_ACCESS_FILENAME }}
            GUNICORN_LOG_ERROR_FILENAME=${{ vars.GUNICORN_LOG_ERROR_FILENAME }}

  redeploy-webhook-call:
    name: Redeploy webhook call
    needs: [build-and-push-to-dockerhub]
    uses: Bodzify/bodzify-server-management/.github/workflows/call-redeployment-webhook.yml@main
    with:
      env: TEST
    secrets: inherit
