name: Audio Fingerprinter CI

on:
  push:
    branches: [main, dev, improve-deployment]
  pull_request:
    branches: [main, dev, improve-deployment]
env:
  DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
  IMAGE_REPO: ${{ vars.AUDIO_FINGERPRINTER_IMAGE_REPO }}
  SSH_DESTINATION: ${{ secrets.TEST_SERVER_BODZIFY_USERNAME }}@${{ vars.TEST_SERVER_URL }}
  TEST_SERVER_URL: ${{ vars.TEST_SERVER_URL }}
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-22.04
    environment:
      name: CI_TEST
    env:
      ENV: ${{ vars.ENV }}
      APP_IS_DOCKERIZED: 'false'
      DEBUG: ${{ vars.DEBUG }}
      APP_IS_EXPOSED: ${{ vars.APP_IS_EXPOSED }}
      APP_PORT: ${{ secrets.APP_PORT }}
      POOL_INTERNAL_DIR: ${{ vars.POOL_INTERNAL_DIR }}
      FLASK_LOGS_ARE_NEEDED: ${{ vars.FLASK_LOGS_ARE_NEEDED }}
      FLASK_LOG_INTERNAL_DIR: ${{ vars.FLASK_LOG_INTERNAL_DIR }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies & python requirements
        run: |
          sudo -E bash scripts/install_dependencies.sh
          python -m pip install --upgrade pip && pip install -r requirements.txt

      - name: Add right fpcalc to PATH
        run: echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      - name: Set up filesystem
        run: bash scripts/setup_filesystem.sh

      - name: Run tests
        run: python -m unittest discover

  build-and-push-to-dockerhub:
    name: Build / Push to DockerHub
    needs: tests
    runs-on: ubuntu-latest
    environment:
      name: TEST
    steps:
      - uses: actions/checkout@v4

      - name: Login to Dockerhub
        run: echo "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}" | docker login -u "${{ env.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        env:
          IMAGE_TAG: ${{ vars.IMAGE_TAG }}
        with:
          context: .
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_REPO }}:${{ env.IMAGE_TAG }}
          build-args: |
            APP_IS_EXPOSED=${{ vars.APP_IS_EXPOSED }}
            POOL_DIR_SYMLINK_TARGET=${{ vars.AUDIO_FINGERPRINTER_POOL_DIR_SYMLINK_TARGET }}
            FLASK_LOG_DIR_SYMLINK_TARGET=${{ vars.AUDIO_FINGERPRINTER_FLASK_LOG_DIR_SYMLINK_TARGET }}
            GUNICORN_LOG_DIR_SYMLINK_TARGET=${{ vars.AUDIO_FINGERPRINTER_GUNICORN_LOG_DIR_SYMLINK_TARGET }}
            POOL_INTERNAL_DIR=${{ vars.POOL_INTERNAL_DIR }}
            FLASK_LOGS_ARE_NEEDED=${{ vars.FLASK_LOGS_ARE_NEEDED }}
            FLASK_LOG_DIR=${{ vars.FLASK_LOG_DIR }}
            FLASK_LOG_APP_FILENAME=${{ vars.FLASK_LOG_APP_FILENAME }}
            FLASK_LOG_ERROR_FILENAME=${{ vars.FLASK_LOG_ERROR_FILENAME }}
            FLASK_LOG_REQUESTS_FILENAME=${{ vars.FLASK_LOG_REQUESTS_FILENAME }}
            GUNICORN_LOG_DIR=${{ vars.AUDIO }}
            GUNICORN_LOG_ACCESS_FILENAME=${{ vars.GUNICORN_LOG_ACCESS_FILENAME }}
            GUNICORN_LOG_ERROR_FILENAME=${{ vars.GUNICORN_LOG_ERROR_FILENAME }}

  redeploy-webhook-call:
    name: Redeploy webhook call
    needs: [build-and-push-to-dockerhub]
    uses: Bodzify/bodzify-server-management/.github/workflows/call-redeployment-webhook.yml@main
    with:
      env: TEST
    secrets: inherit
