name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  tests:
    uses: ./.github/workflows/tests.yaml

  build-and-push-to-dockerhub:
    name: Build / Push to DockerHub
    needs: tests
    runs-on: ubuntu-latest
    environment:
      name: TEST
    steps:
      - uses: actions/checkout@v4

      - name: Login to Dockerhub
        run: echo "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}" | docker login -u "${{ vars.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.AFP_IMAGE_REPO }}:${{ github.ref_name }}
          build-args: |
            FPCALC_INTERNAL_PATH=${{ vars.FPCALC_INTERNAL_PATH }}
            FLASK_LOG_DIR_EXTERNAL=${{ vars.AFP_FLASK_LOG_DIR_EXTERNAL }}
            FLASK_LOG_APP_FILENAME=${{ vars.FLASK_LOG_APP_FILENAME }}
            FLASK_LOG_ERROR_FILENAME=${{ vars.FLASK_LOG_ERROR_FILENAME }}
            FLASK_LOG_REQUESTS_FILENAME=${{ vars.FLASK_LOG_REQUESTS_FILENAME }}
            GUNICORN_LOG_DIR=${{ vars.AFP_GUNICORN_LOG_DIR_EXTERNAL }}
            GUNICORN_LOG_ACCESS_FILENAME=${{ vars.GUNICORN_LOG_ACCESS_FILENAME }}
            GUNICORN_LOG_ERROR_FILENAME=${{ vars.GUNICORN_LOG_ERROR_FILENAME }}

  redeploy-webhook-call:
    name: Redeploy webhook call
    needs: [build-and-push-to-dockerhub]
    uses: BehindTheMusicTree/github-workflows/.github/workflows/call-redeployment-webhook.yml@main
    with:
      env: TEST
    secrets: inherit
